name: Deploy to Dockerhub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Dockerhub Registry
      uses: elgohr/Publish-Docker-Github-Action@2.14
      with:
        name: jackharrhy/duaas
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
